# -*- mode: python ; coding: utf-8 -*-

import os
from pathlib import Path

# Получаем путь к директории проекта
project_dir = Path(__file__).parent.absolute()

# Список дополнительных файлов для включения
datas = [
    (str(project_dir / "*.json"), "."),
    (str(project_dir / "*.csv"), "."),
    (str(project_dir / "*.xlsx"), "."),
    (str(project_dir / "*.md"), "."),
]

# Скрытые импорты для Streamlit и других библиотек
hiddenimports = [
    'streamlit',
    'streamlit.web.cli',
    'streamlit.web.server',
    'streamlit.runtime.scriptrunner',
    'streamlit.elements',
    'streamlit.components',
    'pandas',
    'numpy',
    'plotly',
    'plotly.graph_objects',
    'plotly.express',
    'requests',
    'PIL',
    'PIL.Image',
    'openpyxl',
    'xlsxwriter',
    'prophet',
    'scipy',
    'sklearn',
    'matplotlib',
    'seaborn',
    'altair',
    'pyarrow',
    'tornado',
    'watchdog',
    'gitpython',
    'validators',
    'packaging',
    'toml',
    'pydantic',
    'typing_extensions',
    'click',
    'rich',
    'blinker',
    'cachetools',
    'python-dateutil',
    'pytz',
    'tzlocal',
    'git',
    'gitdb',
    'smmap',
    'tornado.ioloop',
    'tornado.web',
    'tornado.websocket',
    'tornado.gen',
    'tornado.concurrent',
    'tornado.platform.asyncio',
    'tornado.platform.auto',
    'tornado.util',
    'tornado.escape',
    'tornado.httpclient',
    'tornado.httpserver',
    'tornado.netutil',
    'tornado.process',
    'tornado.simple_httpclient',
    'tornado.tcpserver',
    'tornado.tcpclient',
    'tornado.curl_httpclient',
    'tornado.locks',
    'tornado.queues',
    'tornado.stack_context',
    'tornado.testing',
    'tornado.test',
    'tornado.test.util',
    'tornado.test.web_test',
    'tornado.test.websocket_test',
    'tornado.test.wsgi_test',
    'tornado.test.httpserver_test',
    'tornado.test.httpclient_test',
    'tornado.test.curl_httpclient_test',
    'tornado.test.simple_httpclient_test',
    'tornado.test.netutil_test',
    'tornado.test.ioloop_test',
    'tornado.test.process_test',
    'tornado.test.gen_test',
    'tornado.test.concurrent_test',
    'tornado.test.locks_test',
    'tornado.test.queues_test',
    'tornado.test.stack_context_test',
    'tornado.test.log_test',
    'tornado.test.escape_test',
    'tornado.test.util_test',
    'tornado.test.options_test',
    'tornado.test.httputil_test',
    'tornado.test.locale_test',
    'tornado.test.parse_test',
    'tornado.test.template_test',
    'tornado.test.websocket_test',
    'tornado.test.wsgi_test',
    'tornado.test.httpserver_test',
    'tornado.test.httpclient_test',
    'tornado.test.curl_httpclient_test',
    'tornado.test.simple_httpclient_test',
    'tornado.test.netutil_test',
    'tornado.test.ioloop_test',
    'tornado.test.process_test',
    'tornado.test.gen_test',
    'tornado.test.concurrent_test',
    'tornado.test.locks_test',
    'tornado.test.queues_test',
    'tornado.test.stack_context_test',
    'tornado.test.log_test',
    'tornado.test.escape_test',
    'tornado.test.util_test',
    'tornado.test.options_test',
    'tornado.test.httputil_test',
    'tornado.test.locale_test',
    'tornado.test.parse_test',
    'tornado.test.template_test',
]

a = Analysis(
    ['launcher.py'],
    pathex=[str(project_dir)],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='WB_Dashboard',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)